### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by z8a** [dahmadjid/Firebase-idf#3]
Hi Dahmadjid,
thank you very much for your project.
Please could you tell me who is the owner of gtsr1.pem certificate and and when it'll expire?

Many thanks.

**Comment by dahmadjid** [comment]
Its a been a long time since I got them but it should be google's from this website https://pki.goog/repository/
should be around 2036.

and honestly I didnt know if it is the best way to do this. ship certificates with the source code or make users add one. i just grabbed the easiest working solution.
